services:
  mysql:
    image: 'mysql'
    environment:
      - 'MYSQL_DATABASE=SessionAuth'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
    restart: always
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    restart: always
    command: --requirepass redisPassword
